### ISSUE TITLE
Possibly add default windows on startup

### ISSUE THREAD

**Issue by kondor6c** [srhopkins/dotfiles#1]
new -s Primary -n root 'sudo su -'
neww -n psql 'sudo su postgres -c psql'
neww -n ipython ipython
neww -n other bash
neww -n IRC weechat

**Comment by srhopkins** [comment]
Those seem user specific; sounds like a fork to me :) By-the-way its from https://pragprog.com/book/bhtmux/tmux ... which is a cool little book.
